
export const GET_CONTACT_LOAD = "GET_CONTACTS_LOAD"
export const GET_CONTACT_SUCC = "GET_CONTACTS_SUCC"
export const GET_CONTACT_FAIL = "GET_CONTACTS_FAIL"

export const DELETE_CONTACT_SUCC = "DELETE_CONTACT_SUCC"
export const DELETE_CONTACT_FAIL = "DELETE_CONTACT_FAIL"

export const ADD_CONTACT_SUCC = "ADD_CONTACT_SUCC"
export const ADD_CONTACT_FAIL = "ADD_CONTACT_FAIL"

export const TOOGLE_TRUE = "TOOGLE_TRUE"
export const TOOGLE_FALSE = "TOOGLE_FALSE"

export const GET_ONECONTACT_LOAD = "GET_ONECONTACTS_LOAD"
export const GET_ONECONTACT_SUCC = "GET_ONECONTACTS_SUCC"
export const GET_ONECONTACT_FAIL = "GET_ONECONTACTS_FAIL"

export const EDIT_SUCC = "EDIT_SUCC"
export const EDIT_FALSE = "EDIT_FALSE"



